@startuml

skinparam packageStyle rectangle

rectangle Main #EEE;line:EEE; {

    rectangle ClassesList #066;line:066;text:white

    rectangle ClassAutoload #0AA;line:0AA; {
        package FindRequireClass #066;line:066;text:white
        ClassesList *==> FindRequireClass #line:066;

        package ClassFinded #066;line:066;text:white
        FindRequireClass => ClassFinded #line:066;

        package SendClass #066;line:066;text:white
        ClassFinded => SendClass #line:066;
    }

    rectangle Core #666;line:666; {
        package AutoloadRegister #333;line:333;text:white
        ClassAutoload <== AutoloadRegister #line:333;
        SendClass ==> AutoloadRegister #line:066;

        package SetCoreFuncs #333;line:333;text:white
    }

    rectangle FuncsClassesList #28F;line:28F;text:white

    rectangle ClassCoreFuncs #5AF;line:5AF; {
        package ReadListedClasses #28F;line:28F;
        FuncsClassesList *==> ReadListedClasses #line:28F;

        package GetClassesFinded #28F;line:28F;
        ReadListedClasses => GetClassesFinded #line:28F;

        package DeclareFuncs #28F;line:28F;
        GetClassesFinded => DeclareFuncs #line:28F;
        SetCoreFuncs <= DeclareFuncs #line:28F;
    }
    SetCoreFuncs ==> ClassCoreFuncs #line:333;
    AutoloadRegister *== ClassCoreFuncs #line:333;

}

@enduml
