@startuml

class Controller #AA5;line:AA5;text:white

interface SingleConnecterImplement #55A;line:55A;text:white {
    interface singleton

    +static getInst()
}

class RequestsConnecter #88C;line:88C;text:white {
    class Connecter

    -static RequestsAdapter $instance
    -static setInst() : void
    +static getInst() : RequestsAdapter
    +static getRequest() : string
}
SingleConnecterImplement <. RequestsConnecter #line:55A;
Controller ==o RequestsConnecter #line:AA5;

interface RequestsImplement #A55;line:A55;text:white {
    interface adaptater

    +getRequest() : string
}
RequestsConnecter ..> RequestsImplement #line:A55;

class RequestsAdapter #C88;line:C88;text:white {
    class adapter

    -Request $_requests = null
    +getRequest() : string
}
RequestsImplement <. RequestsAdapter #line:A55;
RequestsConnecter ==* RequestsAdapter #line:C88;

class Requests #A5A;line:A5A;text:white {
    class externe

    -string $_request = '/'
    +getRequest() : string
}
RequestsAdapter ==* Requests #line:A5A;

@enduml
