@startuml

top to bottom direction

actor User #888;line:888;

package "WebSite Menu" as WebSite #999;line:999; {
    rectangle "browse Categories" #595;line:595; {
        usecase "Sort Categorie" as SortCategories #595;line:050;
    }
    usecase "page Home" as PageHome #999;line:555;
}
User ==> WebSite #line:444;

package Home #999;line:999; {
    rectangle "browse Authors" #55F;line:55F; {
        usecase "Link Author" as LinkAuthors #55F;line:11F;
        usecase "Sort Author" as SortAuthors #55F;line:11F;
    }
    rectangle "last articles" #9EE;line:9EE; {
        usecase "all articles" as AllArticles #9EE;line:5AA;
        usecase "link article" as LinkLastArticle #9EE;line:5AA;
    }
}
PageHome ==> Home #line:444;

package Articles #9EE;line:9EE; {
    rectangle "Sort by" as SortBy #9EE;line:199; {
        usecase "categorie" as SortByCategorie #595;line:595;
        usecase "author" as SortByAuthor #55F;line:55F;
    }
    SortCategories ==> SortByCategorie #line:050;
    SortAuthors ==> SortByAuthor #line:11F;

    rectangle "browse articles" as BrowseArticles #9EE;line:199; {
        usecase "link article" as LinkBrowseArticle #9EE;line:9EE;
    }
    SortBy --> BrowseArticles #line:199;
}
AllArticles --> Articles #line:199;

package Article #9EE;line:9EE; {
    rectangle "read article" #9EE;line:199; {
        usecase "link categorie" as SortArticleCategorie #595;line:595;
        SortByCategorie <== SortArticleCategorie #line:050;

        rectangle "Author of Aricle" #55F;line:55F; {
            usecase "link author" as LinkArticleAuthor #55F;line:11F;
            usecase "sort article" as SortArticlesAuthor #55F;line:11F;
            SortByAuthor <== SortArticlesAuthor #line:11F;
        }
    }
}
LinkLastArticle ==> Article #line:199;
LinkBrowseArticle ==> Article #line:199;

package Author #55F;line:55F; {
    rectangle "read author profil" #55F;line:11F; {
        usecase "Sort Articles" as SortAuthorArticles #55F;line:11F;
        SortByAuthor <== SortAuthorArticles #line:11F;
    }
}
LinkArticleAuthor ==> Author #line:11F;

@enduml
